## Data Analysis: 
### NumPy

Data analysis involves a  broad set of activities to clean, process and transform a data collection to learn from it. Python is commonly used as a programming language to perform data analysis because of many tools such as jupyter notebook, pandas and bokeh, are written in python and can be quickly applied rather than coding your own data analysis libraries from scratch.
it includes:
import data sets
clean and prepare data for analysis
manipulate pandas DataFrame
summarize data
building data piplines

Numpy:
stands for Numerical python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays.
Using NumPy, mathematical and logical operations on arrays can be performed.
Using NumPy, a developer can perform the following operations-
mathematical and logical operatioms on arrays.
Fourier transforms and routines for shape manipulation
Operations related to linear algebra.NumPy has in-built functions for linear algebra and random number generation.

Array creation using NumPy
The most important object defined in NumPy is an N-dimensional array type called ndarray. It describes the collection of items of the same type. Items in the collection can be accessed using a zero-based index.
Numpy is a library installed in python made by someone else, not an in-built feature of python. There is another in-built library called array which has some basic modules for operations on arrays but does not work very well with matrices.
Also, NumPy is mostly used in Image Processing Task and Machine Learning since we work with a lot of variables there,but not with data analysis.

NumPy's main object is the homogenous multidimensional array. 
It is a table of elements(usually numbers), all of the same type, indexed by a tuple of positive integers.
In NumPy dimensions are called axes. The number of axes is called rank.
NumPy's array class is called ndarray. It is also known by the alias array.
[[1,2,3],
 [4,2,5]]
 here, rank=2 as it is a 2-dimensional array or has 2 axes.
 first dimension(axis) length=2, second dimension length=3
 overall shape can be expressed as (2,3)

In [2]:
import numpy as np   
#anaconda comes pre-installed with data analysis packages, 
#other places you have to do pip install

In [3]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [4]:
print(a)

[1 2 3 4]


In [5]:
type(a)

numpy.ndarray

In [6]:
a.ndim

1

In [7]:
a.shape

(4,)

In [8]:
a.size   
#size function basically gives total number of elements ie, product of 
#axis lengths

4

In [9]:
a.dtype  
#gives the type of the elements of array.int32 means 32 bit integer.
#ie, the amount of space utilized by each and every element of the array

dtype('int32')

In [10]:
b=np.array([[1,2,3,4],
           [5,6,7.6,8]])
b
#when you enter diff data type elements array automatically converts them 
#into a single data type

array([[1. , 2. , 3. , 4. ],
       [5. , 6. , 7.6, 8. ]])

In [12]:
c=np.array([[1,2,3,'4'],
           [5,6,7.6,8]])
c
#string precedent over float over integer. this is because string is most 
#compatible for all entries

array([['1', '2', '3', '4'],
       ['5', '6', '7.6', '8']], dtype='<U32')

In [30]:
d=np.array([[1,2,3,4],
           [5,6,7,8]])
d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
d.shape

(2, 4)

In [16]:
d.size

8

In [17]:
d.ndim

2

In [20]:
d.dtype

dtype('int32')

In [21]:
type(d)

numpy.ndarray

Array creation:
for eg, you can create an array from a regular python list or tuple using the array function. The type of the resulting array is deduced from the type of elements in the sequences.
often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.
For eg, np.zeeros, np.ones, nnp.full, np.empty, etc

In [22]:
arr=np.array([[1,2,3,4],
           [5,6,7,8]], dtype= float)
arr

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [29]:
arr.shape

(2, 4)

In [23]:
arr.dtype

dtype('float64')

In [31]:
a3d=np.array([[[1,2,3,4],
           [5,6,7,8],
              [2,4,6,8]]])
a3d

array([[[1, 2, 3, 4],
        [5, 6, 7, 8],
        [2, 4, 6, 8]]])

In [34]:
a3d=np.array([[[1,2,3,4],
               [5,6,7,8]],
              
              [[10,20,30,40],
               [20,40,60,80]]], dtype = float)
a3d

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[10., 20., 30., 40.],
        [20., 40., 60., 80.]]])

In [27]:
a3d.ndim

3

In [28]:
a3d.shape

(2, 2, 4)

In [15]:
ad=np.array([[[1,2,3,4],
               [5,6,7,8]],
              [[100,200,300,400],
               [200,400,600,800]],
              [[10,20,30,40],
               [20,40,60,80]]], dtype = float)
ad

array([[[  1.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.]],

       [[100., 200., 300., 400.],
        [200., 400., 600., 800.]],

       [[ 10.,  20.,  30.,  40.],
        [ 20.,  40.,  60.,  80.]]])

In [37]:
ad.shape

(3, 2, 4)

In [39]:
ad.ndim

3

In [41]:
#arrays can also be made from tuples 
np.zeros((3,4))
#by default: float format

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
np.zeros((3,4),dtype = str)

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

In [44]:
np.ones((4,3),dtype= int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [45]:
np.ones((4,3,1),dtype= int)    #(rows, layers, columns)

array([[[1],
        [1],
        [1]],

       [[1],
        [1],
        [1]],

       [[1],
        [1],
        [1]],

       [[1],
        [1],
        [1]]])

In [46]:
np.ones((1,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

Digital image processing is the use of a digital computer to process digital images through an algorithm.
types of images:
black & white, grayscale, colored
In digitl imaging, a pixel(or picture element) is the smallest item of information in an image. Pixels are arranged in a 2-dimensional grid, represented using squares. pixels are smallest unit of digital display.
upto millions of pixels make up an image or a video on a device's screen.
for eg: if pixels are made of binary numbers where 1 is for black and 0 is for white then a simple black and white picture can be created using binary. 

In [3]:
np.full((3,4),7.5)

array([[7.5, 7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5, 7.5]])

In [4]:
np.full((3,4),7.5, dtype=int)  
#does not round off, but removes the decimal part

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [19]:
list(range(3,10))

[3, 4, 5, 6, 7, 8, 9]

In [6]:
list(range(3,10,2))

[3, 5, 7, 9]

In [20]:
np.arange(3,10) 
#arange is inclusive of start number and exclusive of end number 
#like range function

array([3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(3,10,2) 
#you are able to control stepsize but not able to control no. of elemeents

array([3, 5, 7, 9])

In [9]:
np.arange(10,3,-2)

array([10,  8,  6,  4])

In [10]:
np.arange(3,10,3)  

array([3, 6, 9])

In [11]:
np.linspace(3,10,3)  
#linspace divides elements equally spaced as in equal difference b/w each 
#element, the previous one and the one after.
#here we are able to control no of elements but step size is decided based 
#on how many numbers we need b/w the boundaries.

array([ 3. ,  6.5, 10. ])

In [12]:
np.linspace(2,10,4)
#note that the space is due to float values. equal spaces since this is 
#in matrix form.

array([ 2.        ,  4.66666667,  7.33333333, 10.        ])

In [13]:
np.linspace(2,10,5)
#linspace is inclusive of both start and end numbers.

array([ 2.,  4.,  6.,  8., 10.])

In [14]:
list(np.linspace(2,10,5))

[2.0, 4.0, 6.0, 8.0, 10.0]

In [16]:
ad

array([[[  1.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.]],

       [[100., 200., 300., 400.],
        [200., 400., 600., 800.]],

       [[ 10.,  20.,  30.,  40.],
        [ 20.,  40.,  60.,  80.]]])

In [17]:
ad.shape

(3, 2, 4)

In [ ]:
##reshaping Array
#Reshaping is allowed when the size of array remains samebefore and 
#after reshaping (so we don't lose any data or generate any new data)
#3*2*4 can be 2*3*4 or 8*3 or 24*1 or 6*4 or 3*2*4*1*1 etc etc

In [22]:
ads = ad.reshape((3,8)) 
ads

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.],
       [100., 200., 300., 400., 200., 400., 600., 800.],
       [ 10.,  20.,  30.,  40.,  20.,  40.,  60.,  80.]])

In [25]:
ads = ad.reshape((3,2,2,2)) 
ads

array([[[[  1.,   2.],
         [  3.,   4.]],

        [[  5.,   6.],
         [  7.,   8.]]],


       [[[100., 200.],
         [300., 400.]],

        [[200., 400.],
         [600., 800.]]],


       [[[ 10.,  20.],
         [ 30.,  40.]],

        [[ 20.,  40.],
         [ 60.,  80.]]]])

In [26]:
ads = ad.reshape((24,1)) 
ads

array([[  1.],
       [  2.],
       [  3.],
       [  4.],
       [  5.],
       [  6.],
       [  7.],
       [  8.],
       [100.],
       [200.],
       [300.],
       [400.],
       [200.],
       [400.],
       [600.],
       [800.],
       [ 10.],
       [ 20.],
       [ 30.],
       [ 40.],
       [ 20.],
       [ 40.],
       [ 60.],
       [ 80.]])

In [27]:
ads = ad.reshape((24)) 
ads 
#this is called flattening of array

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8., 100., 200., 300.,
       400., 200., 400., 600., 800.,  10.,  20.,  30.,  40.,  20.,  40.,
        60.,  80.])

In [28]:
ad.flatten()  #this function does the same

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8., 100., 200., 300.,
       400., 200., 400., 600., 800.,  10.,  20.,  30.,  40.,  20.,  40.,
        60.,  80.])

### Indexing

In [183]:
a3d

array([[[1, 2, 3, 4],
        [5, 6, 7, 8],
        [2, 4, 6, 8]]])

In [37]:
ai=np.array([[1,2,23,4],
           [5,6,17,8],
              [12,4,60,0]])
ai

array([[ 1,  2, 23,  4],
       [ 5,  6, 17,  8],
       [12,  4, 60,  0]])

In [39]:
ai.ndim

2

In [38]:
ai[0]

array([ 1,  2, 23,  4])

In [40]:
ai[0][2]

23

### Integer array Indexing

In [43]:
ai

array([[ 1,  2, 23,  4],
       [ 5,  6, 17,  8],
       [12,  4, 60,  0]])

In [44]:
#suppose we want 2, 17,12,0 from the array above. then, 2- (0,1), 17- (1,2)
#12- (2,0), 0- (2,3)
ai[[0,1,2,2],[1,2,0,3]]   
#here, first list consists of row indexes for each element you want and the 
#second list consists of column indexes for the same elements
#there are 2 lists here because given array is 2 dimensional.

array([ 2, 17, 12,  0])

In [45]:
ai[[0,1,2],[0]]

array([ 1,  5, 12])

In [52]:
ai[[1],[2,1,3]]

array([17,  6,  8])

### Boolean Array Indexing
very useful in data analysis!!!!

In [53]:
ai

array([[ 1,  2, 23,  4],
       [ 5,  6, 17,  8],
       [12,  4, 60,  0]])

In [55]:
ai[ai<=5] #checks row-wise

array([1, 2, 4, 5, 4, 0])

In [56]:
#if I have a list l, l+1 does not make sense, will throw error.
l=[1,2,3,4,5]
l

[1, 2, 3, 4, 5]

In [57]:
l+1 #can only concatenate list (not "int") to list

TypeError: can only concatenate list (not "int") to list

In [58]:
#but in case of arrays
ai

array([[ 1,  2, 23,  4],
       [ 5,  6, 17,  8],
       [12,  4, 60,  0]])

In [60]:
ai1= ai+1
ai1  #1 is added to each and every element

array([[ 2,  3, 24,  5],
       [ 6,  7, 18,  9],
       [13,  5, 61,  1]])

In [61]:
list(np.array(l)+1)   #gives you l+1

[2, 3, 4, 5, 6]

In [62]:
 ai*2

array([[  2,   4,  46,   8],
       [ 10,  12,  34,  16],
       [ 24,   8, 120,   0]])

In [63]:
ai**2

array([[   1,    4,  529,   16],
       [  25,   36,  289,   64],
       [ 144,   16, 3600,    0]])

In [64]:
list(np.array(l)**2)

[1, 4, 9, 16, 25]

In [65]:
list(map((lambda x: x**2),l))

[1, 4, 9, 16, 25]

In [68]:
np.array(list(map((lambda x: x ** 2),ai)))   #same as ai**2

array([[   1,    4,  529,   16],
       [  25,   36,  289,   64],
       [ 144,   16, 3600,    0]])

### Element-wise Arithmetic operation
shape of all input arrays must be same.

In [187]:
ai

array([[ 1,  2,  4, 23],
       [ 5,  6,  8, 17],
       [ 0,  4, 12, 60]])

In [191]:
ai1

array([[ 2,  3, 24,  5],
       [ 6,  7, 18,  9],
       [13,  5, 61,  1]])

In [71]:
ai+ai1  #shape of arrays should be same

array([[  3,   5,  47,   9],
       [ 11,  13,  35,  17],
       [ 25,   9, 121,   1]])

In [72]:
ai*ai1  #different from matrix multiplication

array([[   2,    6,  552,   20],
       [  30,   42,  306,   72],
       [ 156,   20, 3660,    0]])

In [73]:
ai-ai1

array([[-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1]])

In [74]:
ai/ai1

array([[0.5       , 0.66666667, 0.95833333, 0.8       ],
       [0.83333333, 0.85714286, 0.94444444, 0.88888889],
       [0.92307692, 0.8       , 0.98360656, 0.        ]])

In [75]:
ai//ai1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [77]:
#matrix multiplication
#p*q and r*s matrices --> only if q=r,
ai2=ai1.T #taking transpose to make it 4*3
ai2

array([[ 2,  6, 13],
       [ 3,  7,  5],
       [24, 18, 61],
       [ 5,  9,  1]])

In [78]:
ai   #this is 3*4

array([[ 1,  2, 23,  4],
       [ 5,  6, 17,  8],
       [12,  4, 60,  0]])

In [79]:
ai.dot(ai2)    #Matrix Multiplication or Dot multiplication

array([[ 580,  470, 1430],
       [ 476,  450, 1140],
       [1476, 1180, 3836]])

In [80]:
#but with this transposed matrix you cannot do element-wise mutiplication
ai*ai2

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [81]:
ai

array([[ 1,  2, 23,  4],
       [ 5,  6, 17,  8],
       [12,  4, 60,  0]])

In [83]:
ai.max()  #max in the whole array

60

In [84]:
ai.max(axis=0)    #max in each column axis 0

array([12,  6, 60,  8])

In [86]:
ai.max(axis=1)  #max in row axes

array([23, 17, 60])

In [87]:
ai.min()

0

In [89]:
ai.min(axis=0)

array([ 1,  2, 17,  0])

In [90]:
ai.sum()

142

In [91]:
ai.sum(axis=0)

array([ 18,  12, 100,  12])

In [92]:
ai.mean()   #there is no in-built function for mean in lists
#can also be performed according to axis

11.833333333333334

In [93]:
ai.prod()
#can also be performed according to axis

0

In [95]:
ai

array([[ 1,  2, 23,  4],
       [ 5,  6, 17,  8],
       [12,  4, 60,  0]])

In [94]:
ai.cumsum()   #cummulative sum

array([  1,   3,  26,  30,  35,  41,  58,  66,  78,  82, 142, 142])

In [96]:
ai.cumsum(axis=0)

array([[  1,   2,  23,   4],
       [  6,   8,  40,  12],
       [ 18,  12, 100,  12]])

In [97]:
ai.cumprod()

array([          1,           2,          46,         184,         920,
              5520,       93840,      750720,     9008640,    36034560,
       -2132893696,           0])

In [98]:
ai.cumprod(axis=1)

array([[   1,    2,   46,  184],
       [   5,   30,  510, 4080],
       [  12,   48, 2880,    0]])

### Random Array Generation

In [99]:
import random

In [107]:
random.randint(3,10)
#BOTH 3 AND 10 AE INCLUSIVE

10

In [109]:
np.random.randint(3,10)  #we don't need to import random for this
#DIFFERENCE IS THAT IN THIS CASE 3 IS INCLUSIVE BUT 10 IS NOT INCLUSIVE.

6

In [112]:
#advantage of using this is that we can generate and work with arrays here
np.random.randint(3,10, (2,3))
#np: package numpy, random: module, randint: method

array([[4, 5, 6],
       [7, 3, 3]])

In [127]:
np.random.randn(2,4) 
#mostly ranges bwtween -3 to 3
#only need to pass the shape, range is as written above
#Return a sample (or samples) from the "standard normal" distribution.

array([[ 1.21894331,  0.84735203, -1.53610625, -2.70631498],
       [ 0.29212303, -0.766356  , -0.72691955,  0.10442109]])

In [133]:
np.random.rand(3,4)
#Random values in a given shape.
#Create an array of the given shape and populate it with random samples 
#from a uniform distribution over ``[0, 1)``.
#mostly used in probability or accuracy operations in ML

array([[0.87458908, 0.7903298 , 0.42088324, 0.6209898 ],
       [0.42914153, 0.14873293, 0.28335067, 0.55078649],
       [0.99494965, 0.62266464, 0.84840142, 0.40892132]])

In [134]:
np.random.uniform(3,10, (2,3))
#rand function gives uniform distribution between range [0,1) whereas 
#in uniform function you can give your own range for uniform distribution

array([[9.11991477, 5.99062477, 6.64477955],
       [5.0861112 , 6.96684835, 9.92094108]])

In [135]:
l

[1, 2, 3, 4, 5]

In [143]:
np.random.choice(l,(3,4))
#Generates a random sample from a given 1-D array
#syntax--> choice(a, size=None, replace=True, p=None)

array([[4, 5, 2, 5],
       [4, 5, 1, 5],
       [4, 1, 3, 1]])

In [144]:
np.random.choice(10,(3,4))

array([[2, 6, 2, 6],
       [9, 3, 0, 5],
       [2, 4, 8, 3]])

In [147]:
l1=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

In [178]:
o1=np.random.choice(l1,(2,3,3), False)
o1
#False means no repeats.

array([[[14,  3, 12],
        [ 5, 11,  8],
        [ 4,  7, 16]],

       [[18,  1,  6],
        [17, 19, 10],
        [13, 20, 15]]])

### Other functions:

In [150]:
np.sin(np.pi)

1.2246467991473532e-16

In [151]:
np.cos((np.pi)/4)

0.7071067811865476

In [152]:
np.cos(np.pi)

-1.0

In [153]:
np.e

2.718281828459045

In [154]:
np.sqrt(256)

16.0

In [155]:
np.power(2,6)
#integer output

64

In [157]:
import math
math.pow(2,6)
#function is pow here and output is in float

64.0

In [160]:
a=np.array(l)

In [161]:
a

array([1, 2, 3, 4, 5])

In [162]:
np.power(a,4)

array([  1,  16,  81, 256, 625], dtype=int32)

In [163]:
np.power(ai,4)

array([[       1,       16,   279841,      256],
       [     625,     1296,    83521,     4096],
       [   20736,      256, 12960000,        0]], dtype=int32)

In [164]:
np.power(l,4)  #converted list to give output in array

array([  1,  16,  81, 256, 625], dtype=int32)

In [165]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [ ]:
#np.(press Tab button keyboard) to see all functions 

In [166]:
ai

array([[ 1,  2, 23,  4],
       [ 5,  6, 17,  8],
       [12,  4, 60,  0]])

In [168]:
ai.sort() 
ai
#a.sort(axis=-1, kind=None, order=None)
#Sort an array in-place.
#axis : int, optional
#Axis along which to sort. Default is -1, which means sort along the
#last axis.

array([[ 1,  2,  4, 23],
       [ 5,  6,  8, 17],
       [ 0,  4, 12, 60]])

In [169]:
ai.sort?

In [176]:
o

array([[[ 4, 13, 20],
        [ 6, 14, 15],
        [ 5, 16, 18]],

       [[ 8, 10, 19],
        [ 7,  9, 17],
        [ 2,  3, 12]]])

In [175]:
o.sort()
o

array([[[ 4, 13, 20],
        [ 6, 14, 15],
        [ 5, 16, 18]],

       [[ 8, 10, 19],
        [ 7,  9, 17],
        [ 2,  3, 12]]])

In [179]:
o1

array([[[14,  3, 12],
        [ 5, 11,  8],
        [ 4,  7, 16]],

       [[18,  1,  6],
        [17, 19, 10],
        [13, 20, 15]]])

In [180]:
o1.sort(axis=0)

In [181]:
o1

array([[[14,  1,  6],
        [ 5, 11,  8],
        [ 4,  7, 15]],

       [[18,  3, 12],
        [17, 19, 10],
        [13, 20, 16]]])

In [193]:
ai1

array([[ 2,  3, 24,  5],
       [ 6,  7, 18,  9],
       [13,  5, 61,  1]])

In [194]:
d1=np.sort(ai1)

In [195]:
d1

array([[ 2,  3,  5, 24],
       [ 6,  7,  9, 18],
       [ 1,  5, 13, 61]])

In [196]:
np.sort(ai1, axis=0)

array([[ 2,  3, 18,  1],
       [ 6,  5, 24,  5],
       [13,  7, 61,  9]])

In [197]:
np.sort(ai1, axis=None)  
#flattens(converts into 1-D array) the array then sorts

array([ 1,  2,  3,  5,  5,  6,  7,  9, 13, 18, 24, 61])